const actions = {
  CLEAN_STATE: 'CLEAN_STATE',
  MAKE_ERROR_MESSAGE: 'MAKE_ERROR_MESSAGE',

  // AUTH
  AUTH_UPDATE: 'AUTH_UPDATE',
  LOG_IN_REQUEST: 'LOG_IN_REQUEST',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  // TASKS
  GET_TASKS: 'GET_TASKS',
  TASKS_UPDATE: 'TASKS_UPDATE',
  TOGGLE_TASK: 'TOGGLE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  ADD_TASK: 'ADD_TASK'
}

export default actions
